# Generated by Django 4.2.13 on 2024-06-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_generate_report', 'Can generate report'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
